In [6]:
from astropy.io import fits

import matplotlib.pyplot as plt
%matplotlib inline

import tarfile
from astropy.utils.data import download_file
url = 'http://data.astropy.org/tutorials/UVES/data_UVES.tar.gz'
f = tarfile.open(download_file(url, cache = True), mode = 'r|*')
working_dir_path = 'C:/Users/Administrator/Desktop/donghun/AA'
#f.extractall(path = working_dir_path)

from glob import glob
import os
import numpy as np
from astropy.wcs import WCS
from astropy.io import fits

globpath = os.path.join(working_dir_path, 'UVES/*.fits')
#print('globpath : ', globpath)
filelist = glob(globpath)
filelist.sort()

Filename: C:/Users/Administrator/Desktop/donghun/AA\UVES\r.UVES.2011-08-11T232352.266-A01_0000.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU     609   (42751,)   float32   
None


In [17]:
sp = fits.open(filelist[0])

print(sp.info())

<class 'astropy.io.fits.hdu.hdulist.HDUList'>
Filename: C:/Users/Administrator/Desktop/donghun/AA\UVES\r.UVES.2011-08-11T232352.266-A01_0000.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU     609   (42751,)   float32   
None


In [39]:
import re

comp = re.compile('/')



header = sp[0].header
for i in header:
    print(i)

print(header)

#print(header['ESO TEL PARANG START'])

SIMPLE
BITPIX
NAXIS
NAXIS1
EXTEND
DATE
CTYPE1
BUNIT
CRVAL1
CRPIX1
CDELT1
ORIGIN
TELESCOP
INSTRUME
OBJECT
RA
DEC
EQUINOX
RADESYS
MJD-OBS
DATE-OBS
UTC
LST
PI-COI
OBSERVER
DATAMD5
PIPEFILE
DATAMIN
DATAMAX
EXPTIME
BNOISE
ESO OBS DID
ESO OBS EXECTIME
ESO OBS GRP
ESO OBS ID
ESO OBS NAME
ESO OBS OBSERVER
ESO OBS PI-COI ID
ESO OBS PI-COI NAME
ESO OBS PROG ID
ESO OBS TARG NAME
ESO OBS START
ESO OBS TPLNO
ESO TPL DID
ESO TPL ID
ESO TPL NAME
ESO TPL PRESEQ
ESO TPL START
ESO TPL VERSION
ESO TPL NEXP
ESO TPL EXPNO
ESO TEL DID
ESO TEL ID
ESO TEL DATE
ESO TEL ALT
ESO TEL AZ
ESO TEL GEOELEV
ESO TEL GEOLAT
ESO TEL GEOLON
ESO TEL OPER
ESO TEL FOCU ID
ESO TEL FOCU LEN
ESO TEL FOCU SCALE
ESO TEL FOCU VALUE
ESO TEL PARANG START
ESO TEL AIRM START
ESO TEL AMBI FWHM START
ESO TEL AMBI PRES START
ESO TEL AMBI WINDSP
ESO TEL AMBI WINDDIR
ESO TEL AMBI RHUM
ESO TEL AMBI TEMP
ESO TEL MOON RA
ESO TEL MOON DEC
ESO TEL TH M1 TEMP
ESO TEL TRAK STATUS
ESO TEL DOME STATUS
ESO TEL CHOP ST
ESO TEL TARG ALPHA
ESO TEL TARG

In [31]:
# info
import matplotlib.pyplot as plt
import pandas as pd

for i in filelist:
    sp = fits.open(i)
    df = pd.DataFrame(sp.info())
    print(df)

Filename: C:/Users/Administrator/Desktop/donghun/AA\UVES\r.UVES.2011-08-11T232352.266-A01_0000.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU     609   (42751,)   float32   
Empty DataFrame
Columns: []
Index: []
Filename: C:/Users/Administrator/Desktop/donghun/AA\UVES\r.UVES.2011-08-11T234521.856-A01_0000.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU     609   (42751,)   float32   
Empty DataFrame
Columns: []
Index: []
Filename: C:/Users/Administrator/Desktop/donghun/AA\UVES\r.UVES.2011-08-12T000651.936-A01_0000.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU     609   (42751,)   float32   
Empty DataFrame
Columns: []
Index: []
Filename: C:/Users/Administrator/Desktop/donghun/AA\UVES\r.UVES.2011-08-12T002805.585-A01_0000.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU     609   (427

In [34]:
# header


for i in filelist:
    sp = fits.open(i)
    
    header = sp[0].header
    #df = pd.DataFrame(header)
    print('##########################\n', header)
    #print(df)

TypeError: expected string or bytes-like object

In [27]:
print(sp[0].data)

[0. 0. 0. ... 0. 0. 0.]


In [29]:
# data
for i in filelist:
    sp = fits.open(i)
    print(sp[0].data)


[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
